import pandas as pd
import numpy as np
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import joblib

def main():
    print("=== 🌲 LIGHTGBM FUSION COPILOT (MICRO + MACRO) ===")

    data_path = "../data/fused_features_dollar_bars.csv"
    print(f"Loading fused data from: {data_path}")
    df = pd.read_csv(data_path)

    # We must load the pre-calculated LABELS for the dollar bars.
    # The labels were generated by dom_labeler_3MTF_v2.py (Asymmetric Triple Barrier)
    label_path = "../data/labeled_dollar_bars_3MTF_v3.csv"
    df_labels = pd.read_csv(label_path)

    # Merge labels back into the fused features (using exact indices)
    # The Dollar Bar labeler preserves indices.
    df = pd.merge(df, df_labels[['Target_Label']], left_index=True, right_index=True)

    # Define EXPLICIT feature list (Preventing Data Leakage)
    # We combine the old 22 Micro/MTF features with the 7 new ZigZag/Stoch features
    features = [
        'Tick_Speed', 'Micro_Trend', 'Macro_Trend', 'Imbalance_L1', 'Imbalance_L2',
        'Imbalance_L3', 'Imbalance_L4', 'Imbalance_L5', 'Imbalance_L6',
        'Imbalance_L7', 'Imbalance_L8', 'Imbalance_L9', 'Imbalance_L10',
        'CVD_Raw', 'CVD_Rolling_10', 'Cancel_Rate_Rolling_10',
        'Trade_Size_Imbalance', 'Spread_ZScore',
        'M5_RSI_7', 'M15_RSI_14', 'ATR_Micro', 'Velocity_Micro',
        # --- THE NEW MACRO GEOMETRY FUSION ---
        'Dist_Micro_R', 'Dist_Micro_S',
        'Dist_Sec_R', 'Dist_Sec_S',
        'Dist_Ter_R', 'Dist_Ter_S',
        'Stoch_State_M1'
    ]

    # Filter features that exist in the dataframe (some old ones might have different names)
    existing_features = [f for f in features if f in df.columns]

    X = df[existing_features]
    y = df['Target_Label']

    print(f"Dataset shape: {X.shape}")
    print(f"Class distribution:\n{y.value_counts()}")

    # Shift labels to 0, 1, 2 for LightGBM
    y_shifted = y + 1

    # Time-Series Split
    X_train, X_test, y_train, y_test = train_test_split(X, y_shifted, test_size=0.2, shuffle=False)

    print("\nTraining LightGBM Copilot with Feature Fusion...")

    clf = lgb.LGBMClassifier(
        n_estimators=1000,
        learning_rate=0.05,
        num_leaves=31,
        class_weight='balanced',
        objective='multiclass',
        random_state=42,
        n_jobs=-1
    )

    clf.fit(X_train, y_train, eval_set=[(X_test, y_test)])

    y_pred = clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    print(f"\n--- EVALUATION RESULTS (FUSION LGBM) ---")
    print(f"Accuracy: {acc*100:.2f}%")
    print("\nClassification Report (0=Downtrend, 1=Range, 2=Uptrend):")
    print(classification_report(y_test, y_pred, zero_division=0))

    # Feature Importances
    print("\nTop 15 Feature Importances (Tree Splits):")
    importances = clf.feature_importances_
    feat_imps = pd.DataFrame({'Feature': existing_features, 'Importance': importances})
    feat_imps = feat_imps.sort_values(by='Importance', ascending=False)
    print(feat_imps.head(15).to_string(index=False))

    # Save Model
    joblib.dump(clf, '../models/lgbm_model_fusion.pkl')
    print("\n✅ Fusion Model saved to Micro_LGBM/models/lgbm_model_fusion.pkl")

if __name__ == "__main__":
    main()
